#!/usr/bin/env bash
set -e

mkdir binary-releases

# adds a file to identify a build as a standalone binary
echo '' >dist/STANDALONE

npx pkg . -t node12-linux-arm64 -o binary-releases/snyk-linux-arm64
npx pkg . -t node12-linux-armv7 -o binary-releases/snyk-linux-armv7
npx pkg . -t node12-win-x64 -o binary-releases/snyk-win-x64-unsigned.exe
npx pkg . -t node12-win-x86 -o binary-releases/snyk-win-x86-unsigned.exe
npx pkg . -t node12-macos-x64 -o binary-releases/snyk-macos-x64


# build docker package
./release-scripts/docker-desktop-release.sh

# sign the windows binary
./release-scripts/sign-windows-binary.sh

# compute checksums
pushd binary-releases
shasum -a 256 snyk-linux-arm64 >snyk-linux-arm64.sha256
shasum -a 256 snyk-linux-armv7 >snyk-linux-armv7.sha256
shasum -a 256 snyk-macos >snyk-macos.sha256
# note: checksum for snyk-win.exe is generated by `sign-windows-binary.sh`
# note: checksum for docker-mac-signed-bundle is generated by `docker-desktop-release.sh`
popd

# removes the file we use to identify a build as a standalone binary
rm dist/STANDALONE

ls -la
